### ISSUE TITLE
FEAT: Add a "Add a new item" button on the "showItemSidebar"?

### ISSUE THREAD

**Issue by ips-coding-challenge** [Shoppingify/frontend#135]
When I start to add items, it feels kinda weird to not be able to chain the "add" action. I need to click on the back button to go back to the shopList and then re-click on "add a new item". I wonder if it would not be better to add a new button "add another item" which will simply redirect to the AddItemSidebar?

**Comment by fajfara** [comment]
Again, sorry I forgot about this one, but yeah that sounds great.
