### ISSUE TITLE
FEAT: Update the list name when we press Enter?

### ISSUE THREAD

**Issue by ips-coding-challenge** [Shoppingify/frontend#136]
It feels unnatural to click on the close icon to update the list name.

**Comment by fajfara** [comment]
Well, would enter then trigger the closing of the shop list edit mode? If enter just saves the list name, that would feel weird.

**Comment by ips-coding-challenge** [comment]
Yes, I think it should close the edit mode ;)

**Comment by fajfara** [comment]
The more i think about this, the less sense it makes. Does the user even know he is edit mode? I added the notification, but what if you miss that? It does open extra options (title changes to input, +/- quantity btns and delete item), but it still feels weird, especially on mobile. For example the icon, we thought its better if it changes to the x icon, but wouldn't that indicate cancel (not saving changes)? I think we should also change that, or perhaps have two icons, one for canceling and one for saving.

**Comment by ips-coding-challenge** [comment]
Should we only have an edit button for the title and also an edit button for each item on the shopping list? On the design, it seems that only one item can be modified at a time.

**Comment by fajfara** [comment]
Hey sorry, totally forgot about this issue. I think we should leave the item edit as it is right now, I feel it makes sense to show edit options on all items at once. So at the moment the enter key should save/change the shop list edit mode. I wouldn't add another button, cause that would mean we would have to change the way items are saved in the list (from real-time to saving on pressing the enter/to save button).
