### ISSUE TITLE
FIX|FEAT: History list overflow

### ISSUE THREAD

**Issue by fajfara** [Shoppingify/frontend#146]
I noticed we added overflow-y on the history list for each month. It seems kind of odd, especially on desktop, because when you scroll on one month, another month doesn't automatically scroll, user has to move their mouse over the next month, this has to be then done for every month. Should we just have it in a similar way that it is on the items page, perhaps also use accordion if there is a large number of items for that month?

**Comment by ips-coding-challenge** [comment]
Oh. I Didn't notice that. I will take care of it. For the accordion, I'm not sure it's needed. In a real case scenario, how many lists a user could make for a month? Maybe 4-5? And I could also limit the maximum history to 12 months for example.
