### ISSUE TITLE
History Items Page vs Items Page

### ISSUE THREAD

**Issue by ips-coding-challenge** [Shoppingify/frontend#55]
The history items page and the items page are pretty similar but with some particularities. At first, I was thinking to adjust the items page ( adding some props ) but I'm not sure anymore. I think we should create a history items page. There will be some duplicate stuff but I think that it will be more maintainable in the end?

What do you think?

**Comment by fajfara** [comment]
We will have to create another page, we will be using router for this right? For the items display, we can reuse the current Item component.
