### ISSUE TITLE
FIX: Category edit

### ISSUE THREAD

**Issue by fajfara** [Shoppingify/frontend#56]
After changing the name of one of the default categories, I can't change the name to the original name.
Also when trying to add a new item to the old name of the category it just gets added to the renamed category?
One example was also Meat and fish, I renamed it to Meat and fish two, I tried renaming it back, won't work. I also tried renaming it to Meat and fis (without one letter) that fails as well.

Also when changing the category name the change is not updated in the shopping list

**Comment by ips-coding-challenge** [comment]
Did you have the latest backend version?

**Comment by fajfara** [comment]
Yeah, I have the latest backend version. I can't reproduce it again, perhaps an issue on my client-side? Will keep it open just in case.
