### ISSUE TITLE
FIX: Sidebar history incorrect behaviour

### ISSUE THREAD

**Issue by fajfara** [Shoppingify/frontend#59]
I was playing around with the sidebar items and I found a small bug, to reproduce:
- Click on an item on the items page to display items info
- Click the edit icon
- Click the cancel button
- Again click on the same item on the items page
- Click back
It takes you to the edit screen instead of the shopping list
This seems like a really minor bug, so no rush :)

**Comment by ips-coding-challenge** [comment]
I tried exactly what you said but wasn't able to reproduce the bug?
