### ISSUE TITLE
FEAT: Statistics Page

### ISSUE THREAD

**Issue by ips-coding-challenge** [Shoppingify/frontend#75]
I'm not sure what the graph is supposed to represent? Furthermore, on the design, there are monthly and yearly stats but there is no way to switch between that. Also, I was wondering if I should process the data on the backend or send everything and the front will do the job?

**Comment by fajfara** [comment]
I assume the graph represents the number of items purchased (all shopping list items quantities for that month combined).
We could just add a button to switch between two categories.
If I understand the part about processing data correctly, you would like to calculate statistics on the client-side? If so, I don't think that's a good idea. I think the backend should process all the data (get the number of items per month, calculate the frequency an item gets picked etc.). I also think the data shouldn't be calculated on every request to the stats endpoint/s, as you should only update the statistics once a list gets completed and cache the results in the DB.
