### ISSUE TITLE
FIX: Sidebar state switching

### ISSUE THREAD

**Issue by fajfara** [Shoppingify/frontend#81]
I thought i was causing the delay of sidebar state switching when I added the AnimatePresence component, but that didn't make too much sense.
So I found out this only seems to happen on the data@test.com account when the user has loads of items, this needs to be checked.

**Comment by fajfara** [comment]
Might be because i am loading shopping list every time the sidebar components change. Issue #88 might fix this, so i will focus on that first.

**Comment by fajfara** [comment]
So i extracted the issue #88 into its own hook, that did nothing to fix this issue :D 
Do you have any idea what could be causing this issue? A the moment when you click to open item in the sidebar it takes a good second or two for the sidebar components to switch 😕

**Comment by ips-coding-challenge** [comment]
Yes, I think I know what causes the issue, but I have a lot more difficulties finding the solution ;). If you look at the re-renders, it re-renders the whole list when you click on an item. I tried with some memorization and useCallback but without results yet. Also, I don't get why the "+" button in the item is constantly rerendering... When you do a search, for example, it rerenders too. 

Well, I think a lot of our perfs problems are just too many unwanted re-renders. But it's not that easy to fix them

**Comment by fajfara** [comment]
Ah, I think I know what it is, framer-motion -.- 
I don't know why but before the stagger children didn't work, for some reason it started working (at least for me), so my only guess is, that it's waiting for those animations to finish. 
I tested this on the master, I removed motion.ul and motion.li components and it works fine now.
