### ISSUE TITLE
FEAT: Extract editable title into own component

### ISSUE THREAD

**Issue by fajfara** [Shoppingify/frontend#85]
I will try to use contentEditable for this ...

**Comment by ips-coding-challenge** [comment]
I almost answered in French :D...

Why not just use an input? Maybe reducing the font size for the title?

**Comment by fajfara** [comment]
Because of the jumping of content, especially on textarea ... I tried calculating the height and adjust when changing modes, but it still not ok. I found an already made component so I will copy that and adjust it for our project.
