### ISSUE TITLE
FEAT: Deleting item

### ISSUE THREAD

**Issue by fajfara** [Shoppingify/frontend#97]
Should removing/deleting an item in the items page also delete it from the shopping list? At the moment it does, remove it from the items page it also removes it from the shopping list.

**Comment by ips-coding-challenge** [comment]
I think it should, but it's more complex than what I thought actually. Because, actually, if we delete an item, it will also be removed from the completed/canceled list. Deleting an item should be reflected on the active list but what about the completed list and canceled list? Isn't it weirder?

**Comment by fajfara** [comment]
Inside history, it should stay, since it is part of the history :D Oh yeah, just saw that removing the item from the items page actually also removes it from the history, from every list. That's not good :D

**Comment by ips-coding-challenge** [comment]
Yes, I would have to handle that in the backend ;).

**Comment by fajfara** [comment]
Perhaps also add a property to deleted item, so on the frontend, it can't be added to the active shop list if the item was removed?

**Comment by ips-coding-challenge** [comment]
Actually, you shouldn't receive deleted items. I will add a deleted_at column in the backend ( it's what we called soft delete ). So only the history mode should receive everything. 
There will be another thing to handle tho. Actually clicking on an item open the sidebar. In the case of a deleted item in the history mode, should we block that possibility or just open the sidebar with the possibility to restore the item?
