### ISSUE TITLE
PERFS: Performances Issues

### ISSUE THREAD

**Issue by ips-coding-challenge** [Shoppingify/frontend#98]
For the performance issue with a lot of data, I think we should first consider to "finish" the application and then think/tackle those issues. ;)

**Comment by fajfara** [comment]
Some issues yes, another no. For example the framer motion issue, I am animating widths which are performance heavy, so changing that can help in the performance. Some issues i would rather tackle sooner than later

**Comment by ips-coding-challenge** [comment]
Yes, I was thinking more of problems that a user could encounter after passing a lot of time in the application ;)
