### ISSUE TITLE
FEAT: Removing category

### ISSUE THREAD

**Issue by fajfara** [Shoppingify/frontend#99]
At the moment there is no way to remove a category. Should we add this functionality?

**Comment by ips-coding-challenge** [comment]
In the case where we handle no items in the category, and renaming category, I'm not sure that we need it. But I was honestly thinking about it lately. So I'm not completely sure. Maybe It'd make sense, but in that case, should we allow to delete every item in the category or only allow to delete empty categories?

**Comment by fajfara** [comment]
It makes sense to delete every category, regardless if it has items or not, right? I would just make it like that and also add some sort of confirmation that the user needs to click to delete the category. Perhaps also add some sort of undo feature (this might be for later if we decide to do it)?

**Comment by ips-coding-challenge** [comment]
Yes. I will have to think about the backend. I will also just "soft delete" the category. But I'm not sure about all the implications :D. But it will not be a problem, it will just maybe take more time than what I'm thinking ;)
